version: "3.8"

services:
  php:
    container_name: sn-php
    build:
      context: ./
      dockerfile: "./docker/php/Dockerfile"
      args:
        - BUILD_UID=${DOCKER_UID}
        - BUILD_GID=${DOCKER_GID}
    environment:
      PHP_IDE_CONFIG: "serverName=host.docker.internal"
    working_dir: /var/www/html
    networks:
      - default
    volumes:
      - ./:/var/www/html:cached
      - ./node_modules:/var/www/html/node_modules:delegated
      - ./public:/var/www/html/public:delegated

  nginx:
    container_name: sn-nginx
    image: wodby/nginx
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: php
      NGINX_SERVER_ROOT: /var/www/html/public
    depends_on:
      - php
      - mariadb
    volumes:
      - ./public:/var/www/html/public:delegated
      - ./storage/app/public:/var/www/html/public/storage:delegated
    networks:
      - default
      - traefik-gateway
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-gateway"
      - "traefik.http.routers.sn-nginx.rule=Host(`screen-snack.localhost`)"
      - "traefik.http.routers.sn-nginx.entrypoints=http"
      - "traefik.http.routers.sn-nginx.tls=false"

  mariadb:
    container_name: sn-mariadb
    image: mariadb:10.4
    command: --init-file /data/application/init.sql
    volumes:
      - ./docker/mariadb/init.sql:/data/application/init.sql
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: screen_snack
      MYSQL_ROOT_PASSWORD: screen-snack
      MYSQL_USER: screen-snack
      MYSQL_PASSWORD: screen-snack
    ports:
      - "127.0.0.1:34069:3306"
  redis:
    image: redis:4-alpine
    container_name: sn-redis
    volumes:
      - redis:/data

volumes:
  mariadb:
    driver: local
  redis:
    driver: local

# Make the externally created network "traefik-gateway" available as network "default"
# docker network create traefik-gateway
networks:
  traefik-gateway:
    name: traefik-gateway
    external: true
